pipeline:
  publish:
    image: plugins/docker
    repo: jsoude/jenkins-slave
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
 
  slack:
    image: plugins/slack
secrets: [ slack_webhook ]
